services:
  db:
    image: mysql:lts
    network_mode: bridge
    environment:
      - MYSQL_ROOT_PASSWORD=piepiepie12@A
    volumes:
      - data:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  data:
