version: "3"

services:
  backend:
    container_name: infisical-backend
    restart: unless-stopped
    image: infisical/infisical:latest-postgres
    pull_policy: always
    env_file: .env
    ports:
      - 8081:8080
    environment:
      - NODE_ENV=production
    network_mode: bridge


volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
