networks:
  fiber:
    driver: bridge

services:
  postgres:
    container_name: postgres
    networks:
      - fiber
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=thaian12@A
      - POSTGRES_USER=justapie
      - POSTGRES_DB=justapie
    volumes:
      - data:/var/lib/postgresql
    restart: always

  pgadmin:
    container_name: pgadmin
    networks:
      - fiber
    image: 'elestio/pgadmin'
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=justapie06@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=thaian12@A
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - '8080:8080'

volumes:
  data:
